-- I used an online decoder to decode an xml to JSON, I'm surprised this actually worked well!
-- this dude
-- ^ this dude

return[[
	{
  "roblox": {
    "External": [
      "null",
      "nil"
    ],
    "utterance": [
      {
        "#text": "Hello",
        "utterance": [
          {
            "#text": "Hi",
            "utterance": [
              "Hi there!",
              "Hi everyone"
            ]
          },
          {
            "#text": "Howdy",
            "utterance": "Howdy partner!"
          },
          {
            "#text": "Greetings",
            "utterance": [
              "Greetings eveyone",
              "Greetings robloxians!",
              "Seaons greetings!"
            ]
          },
          {
            "#text": "Welcome",
            "utterance": [
              "Welcome to my place",
              "Welcome to our base",
              "Welcome to my barbecque"
            ]
          },
          "Hey there!",
          {
            "#text": "What's up?",
            "utterance": [
              "How are you doing?",
              "How's it going?",
              "What's new?"
            ]
          },
          {
            "#text": "Good day",
            "utterance": [
              "Good morning",
              "Good afternoon",
              "Good evening",
              "Good night"
            ]
          },
          {
            "#text": "Silly",
            "utterance": [
              "Waaaaaaaz up?!",
              "Hullo!",
              "Behold greatness, mortals!"
            ]
          },
          {
            "#text": "Holidays",
            "utterance": [
              "Happy New Year!",
              "Happy Valentine's Day!",
              "Beware the Ides of March!",
              "Happy Easter!",
              "Happy 4th of July!",
              "Happy Thanksgiving!",
              "Happy Halloween!",
              "Happy Hanukkah!",
              "Merry Christmas!",
              "Happy Holidays!"
            ]
          }
        ]
      },
      {
        "#text": "Goodbye",
        "utterance": [
          {
            "#text": "Good Night",
            "utterance": [
              "Sweet dreams",
              "Go to sleep!",
              "Lights out!",
              "Bedtime"
            ]
          },
          {
            "#text": "Later",
            "utterance": [
              "See ya later",
              "Later gator!",
              "See you tomorrow"
            ]
          },
          {
            "#text": "Bye",
            "utterance": "Hasta la bye bye!"
          },
          "I'll be right back",
          "I have to go",
          {
            "#text": "Farewell",
            "utterance": [
              "Take care",
              "Have a nice day",
              "Goodluck!",
              "Ta-ta for now!"
            ]
          },
          {
            "#text": "Peace",
            "utterance": [
              "Peace out!",
              "Peace dudes!",
              "Rest in pieces!"
            ]
          },
          {
            "#text": "Silly",
            "utterance": [
              "To the batcave!",
              "Over and out!",
              "Happy trails!",
              "I've got to book it!",
              "Tootles!",
              "Smell you later!",
              "GG!",
              "My house is on fire! gtg."
            ]
          }
        ]
      },
      {
        "#text": "Friend",
        "utterance": [
          "Wanna be friends?",
          {
            "#text": "Follow me",
            "utterance": [
              "Come to my place!",
              "Come to my base!",
              "Follow me, team!"
            ]
          },
          {
            "#text": "Your place is cool",
            "utterance": [
              "Your place is fun",
              "Your place is awesome",
              "Your place looks good"
            ]
          },
          {
            "#text": "Thank you",
            "utterance": [
              "Thanks for playing",
              "Thanks for visiting",
              "Thanks for everything",
              "No thank you"
            ]
          },
          {
            "#text": "No problem",
            "utterance": [
              "Don't worry",
              "That's ok"
            ]
          },
          {
            "#text": "You are ...",
            "utterance": [
              "You are great!",
              "You are good!",
              "You are cool!",
              "You are funny!",
              "You are silly!",
              "You are awesome!"
            ]
          },
          {
            "#text": "I like ...",
            "utterance": [
              "I like your name",
              "I like your shirt",
              "I like your place",
              "I like your style"
            ]
          },
          {
            "#text": "Sorry",
            "utterance": [
              "My bad!",
              "I'm sorry",
              "Whoops!",
              "Please forgive me",
              "I forgive you"
            ]
          }
        ]
      },
      {
        "#text": "Questions",
        "utterance": [
          {
            "#text": "Who?",
            "utterance": [
              "Who wants to be my friend?",
              "Who wants to be on my team?",
              "Who made this brilliant game?"
            ]
          },
          {
            "#text": "What?",
            "utterance": [
              "What is your favorite animal?",
              "What is your favorite game?",
              "What is your favorite movie?",
              "What is your favorite TV show?",
              "What is your favorite music?",
              "What are your hobbies?"
            ]
          },
          {
            "#text": "When?",
            "utterance": [
              "When are you online?",
              "When is the new version coming out?",
              "When can we play again?",
              "When will your place be done?"
            ]
          },
          {
            "#text": "Where?",
            "utterance": [
              "Where do you want to go?",
              "Where are you going?",
              "Where am I?!"
            ]
          },
          {
            "#text": "How?",
            "utterance": [
              "How are you today?",
              "How did you make this cool place?"
            ]
          },
          {
            "#text": "Can I...",
            "utterance": [
              "Can I have a tour?",
              "Can I be on your team?",
              "Can I be your friend?",
              "Can I try something?"
            ]
          }
        ]
      },
      {
        "#text": "Answers",
        "utterance": [
          {
            "#text": "You need help?",
            "utterance": [
              "Check out the news section",
              "Check out the help section",
              "Read the wiki!",
              "All the answers are in the wiki!"
            ]
          },
          {
            "#text": "Some people ...",
            "utterance": [
              "Me",
              "Not me",
              "You",
              "All of us",
              "Everyone but you",
              "Builderman!",
              "Telamon!"
            ]
          },
          {
            "#text": "Time ...",
            "utterance": [
              "In the morning",
              "In the afternoon",
              "At night",
              "Tomorrow",
              "This week",
              "This month",
              "Sometime",
              "Sometimes",
              "Whenever you want",
              "Never"
            ]
          },
          {
            "#text": "Animals",
            "utterance": [
              {
                "#text": "Cats",
                "utterance": [
                  "Lion",
                  "Tiger",
                  "Leopard",
                  "Cheetah"
                ]
              },
              {
                "#text": "Dogs",
                "utterance": [
                  "Wolves",
                  "Beagle",
                  "Collie",
                  "Dalmatian",
                  "Poodle",
                  "Spaniel",
                  "Shepherd",
                  "Terrier",
                  "Retriever"
                ]
              },
              {
                "#text": "Horses",
                "utterance": [
                  "Ponies",
                  "Stallions"
                ]
              },
              {
                "#text": "Reptiles",
                "utterance": [
                  "Dinosaurs",
                  "Lizards",
                  "Snakes",
                  "Turtles!"
                ]
              },
              "Hamster",
              "Monkey",
              "Bears",
              {
                "#text": "Fish",
                "utterance": [
                  "Goldfish",
                  "Sharks",
                  "Sea Bass",
                  "Halibut"
                ]
              },
              {
                "#text": "Birds",
                "utterance": [
                  "Eagles",
                  "Penguins",
                  "Turkeys"
                ]
              },
              "Elephants",
              {
                "#text": "Mythical Beasts",
                "utterance": [
                  "Dragons",
                  "Unicorns",
                  "Sea Serpents",
                  "Sphinx",
                  "Cyclops",
                  "Minotaurs",
                  "Goblins",
                  "Honest Politicians",
                  "Ghosts",
                  "Scylla and Charybdis"
                ]
              }
            ]
          },
          {
            "#text": "Games",
            "utterance": [
              {
                "#text": "Roblox",
                "utterance": [
                  "BrickBattle",
                  "Community Building",
                  "Roblox Minigames"
                ]
              },
              "Action",
              "Puzzle",
              "Strategy",
              "Racing",
              "RPG",
              {
                "#text": "Board games",
                "utterance": [
                  "Chess",
                  "Checkers",
                  "Settlers of Catan",
                  "Tigris and Euphrates",
                  "El Grande",
                  "Stratego",
                  "Carcassonne"
                ]
              }
            ]
          },
          {
            "#text": "Sports",
            "utterance": [
              "Hockey",
              "Soccer",
              "Football",
              "Baseball",
              "Basketball",
              "Volleyball",
              "Tennis",
              {
                "#text": "Watersports",
                "utterance": [
                  "Surfing",
                  "Swimming",
                  "Water Polo"
                ]
              },
              {
                "#text": "Winter sports",
                "utterance": [
                  "Skiing",
                  "Snowboarding",
                  "Sledding",
                  "Skating"
                ]
              },
              {
                "#text": "Adventure",
                "utterance": [
                  "Rock climbing",
                  "Hiking",
                  "Fishing"
                ]
              },
              {
                "#text": "Wacky",
                "utterance": [
                  "Foosball",
                  "Calvinball",
                  "Croquet",
                  "Cricket",
                  "Dodgeball",
                  "Squash"
                ]
              }
            ]
          },
          {
            "#text": "Movies/TV",
            "utterance": [
              "Science Fiction",
              {
                "#text": "Animated",
                "utterance": "Anime"
              },
              "Comedy",
              "Romantic",
              "Action",
              "Fantasy"
            ]
          },
          {
            "#text": "Music",
            "utterance": [
              "Country",
              "Jazz",
              "Rap",
              "Hip-hop",
              "Techno",
              "Classical",
              "Pop",
              "Rock"
            ]
          },
          {
            "#text": "Hobbies",
            "utterance": [
              {
                "#text": "Computers",
                "utterance": [
                  "Building computers",
                  "Videogames",
                  "Coding",
                  "Hacking"
                ]
              },
              {
                "#text": "The Internet",
                "utterance": "lol. teh internets!"
              },
              "Dance",
              "Gynastics",
              {
                "#text": "Martial Arts",
                "utterance": [
                  "Karate",
                  "Judo",
                  "Taikwon Do",
                  "Wushu",
                  "Street fighting"
                ]
              },
              "Listening to music",
              {
                "#text": "Music lessons",
                "utterance": [
                  "Playing in my band",
                  "Playing piano",
                  "Playing guitar",
                  "Playing violin",
                  "Playing drums",
                  "Playing a weird instrument"
                ]
              },
              "Arts and crafts"
            ]
          },
          {
            "#text": "Location",
            "utterance": [
              {
                "#text": "USA",
                "utterance": [
                  {
                    "#text": "West",
                    "utterance": [
                      "Alaska",
                      "Arizona",
                      "California",
                      "Colorado",
                      "Hawaii",
                      "Idaho",
                      "Montana",
                      "Nevada",
                      "New Mexico",
                      "Oregon",
                      "Utah",
                      "Washington",
                      "Wyoming"
                    ]
                  },
                  {
                    "#text": "Midwest",
                    "utterance": [
                      "Illinois",
                      "Indiana",
                      "Iowa",
                      "Kansas",
                      "Michigan",
                      "Minnesota",
                      "Missouri",
                      "Nebraska",
                      "North Dakota",
                      "Ohio",
                      "South Dakota",
                      "Wisconsin"
                    ]
                  },
                  {
                    "#text": "Northeast",
                    "utterance": [
                      "Connecticut",
                      "Delaware",
                      "Maine",
                      "Maryland",
                      "Massachusetts",
                      "New Hampshire",
                      "New Jersey",
                      "New York",
                      "Pennsylvania",
                      "Rhode Island",
                      "Vermont",
                      "Virginia",
                      "West Virginia"
                    ]
                  },
                  {
                    "#text": "South",
                    "utterance": [
                      "Alabama",
                      "Arkansas",
                      "Florida",
                      "Georgia",
                      "Kentucky",
                      "Louisiana",
                      "Mississippi",
                      "North Carolina",
                      "Oklahoma",
                      "South Carolina",
                      "Tennessee",
                      "Texas"
                    ]
                  }
                ]
              },
              {
                "#text": "Canada",
                "utterance": [
                  "Alberta",
                  "British Columbia",
                  "Manitoba",
                  "New Brunswick",
                  "Newfoundland",
                  "Northwest Territories",
                  "Nova Scotia",
                  "Nunavut",
                  "Ontario",
                  "Prince Edward Island",
                  "Quebec",
                  "Saskatchewan",
                  "Yukon"
                ]
              },
              "Mexico",
              "Central America",
              {
                "#text": "Europe",
                "utterance": [
                  {
                    "#text": "Great Britain",
                    "utterance": [
                      "England",
                      "Scotland",
                      "Wales",
                      "Northern Ireland"
                    ]
                  },
                  "France",
                  "Germany",
                  "Spain",
                  "Italy",
                  "Poland",
                  "Switzerland",
                  "Greece",
                  "Romania"
                ]
              },
              {
                "#text": "Asia",
                "utterance": [
                  "China",
                  "India",
                  "Japan",
                  "Korea"
                ]
              },
              {
                "#text": "South America",
                "utterance": [
                  "Argentina",
                  "Brazil"
                ]
              },
              {
                "#text": "Africa",
                "utterance": [
                  "Eygpt",
                  "Swaziland"
                ]
              },
              "Australia",
              "Middle East",
              "Antarctica"
            ]
          },
          {
            "#text": "Age",
            "utterance": [
              "Rugrat",
              "Kid",
              "Teen",
              "Twenties",
              "Old",
              "Ancient",
              "Mesozoic"
            ]
          },
          {
            "#text": "Mood",
            "utterance": [
              "Good",
              "Great!",
              "Not bad",
              "Sad",
              "Hyper",
              "Chill"
            ]
          },
          "Boy",
          "Girl"
        ]
      },
      {
        "#text": "Game",
        "utterance": [
          "Let's build",
          "Let's battle",
          "Nice one!",
          "So far so good!",
          "Lucky shot!",
          "Oh man!"
        ]
      },
      {
        "#text": "Silly",
        "utterance": [
          "Muahahahaha!",
          {
            "#text": "1337",
            "utterance": [
              "i r teh pwnz0r!",
              "w00t!",
              "z0mg h4x!",
              "ub3rR0xXorzage!",
              "all your base are belong to me!"
            ]
          }
        ]
      },
      {
        "#text": "Yes",
        "utterance": [
          "Absolutely!",
          "Rock on!",
          "Totally!",
          "Juice!"
        ]
      },
      {
        "#text": "No",
        "utterance": [
          "Ummm. No.",
          "..."
        ]
      },
      {
        "#text": "Ok",
        "utterance": [
          "Well... ok",
          "Sure"
        ]
      },
      {
        "#text": ":-)",
        "utterance": [
          ":-(",
          ":D",
          ":-O",
          "lol"
        ]
      }
    ]
  }
}
]]